name: Catalog Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./catalog-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
      - name: Grant execute have the executable permission.
        run: chmod +x ./mvnw
      - name: Build with Maven
        run: ./mvnw -ntp verify
#        run: mvn -B package --file catalog-service/pom.xml
#      - name: Build Docker image
#        run: docker build -t catalog-service:latest catalog-service
#      - name: Login to Docker Hub
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#      - name: Push Docker image
#        run: docker push catalog-service:latest